server:
  port: 8765

spring:
  application:
    name: api-gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: contacts_route
#          uri: "lb://contacts-service"
#          predicates:
#            - Path= /api/v1/contacts/**
#        - id: users_route
#          uri: "lb://user-profile-service"
#          predicates:
#            - Path= /api/v1/users/**


  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


jwt:
  secret:
    key1: ${JWT_SECRET:secretkey}